# kubernetes/observability/prometheus-values.yaml
# Custom Helm values for kube-prometheus-stack

# We disable features we don't immediately need to save EC2 memory
defaultRules:
  create: true
alertmanager:
  enabled: false
pushgateway:
  enabled: false

# Grafana Configuration
grafana:
  enabled: true
  adminPassword: "CHANGE_ME_PLEASE" # The native login password for the UI
  
  # Ensure dashboards persist if the pod restarts
  persistence:
    enabled: true
    type: pvc
    size: 2Gi
    
  # Configure Grafana to serve itself cleanly from a subpath (/grafana) instead of root
  grafana.ini:
    server:
      domain: '<YOUR_CUSTOM_DOMAIN>' # e.g. devopsengg.com
      root_url: '%(protocol)s://%(domain)s/grafana/'
      serve_from_sub_path: true

# Prometheus Data Persistence
prometheus:
  enabled: true
  prometheusSpec:
    retention: 5d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
