apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
# Note: In a true production environment, these should not be stored in plain text in git.
# Consider using AWS Secrets Manager with External Secrets Operator or SOPS.
# These values must be Base64 encoded.
data:
  # Example: echo -n "admin" | base64 -> YWRtaW4=
  MYSQL_USER: "YWRtaW4="
  MYSQL_PASSWORD: "SzhzJm1pY3Jvc3Zj" # Base64 of your mysql password
  SECRET_KEY: "MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  MYSQL_SERVER: "myapp-ue1-dev-eks-appmysql.c21q4i0oom0q.us-east-1.rds.amazonaws.com" # Replace with your RDS endpoint
  MYSQL_PORT: "3306"
  MYSQL_DB_LOGIN: "login_db"
  MYSQL_DB_FILE: "file_db"
  AWS_REGION_NAME: "us-east-1"
  AWS_BUCKET_NAME: "myapp-ue1-dev-eks-app-files"
  LOGIN_SERVICE_URL: "https://devopsengg.com"