apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
# Note: In a true production environment, these should not be stored in plain text in git.
# Consider using AWS Secrets Manager with External Secrets Operator or SOPS.
# These values must be Base64 encoded.
data:
  # Example: echo -n "admin" | base64 -> YWRtaW4=
  MYSQL_USER: "YWRtaW4="
  MYSQL_PASSWORD: "<BASE64_MYSQL_PASSWORD>" # Base64 of your mysql password
  SECRET_KEY: "<BASE64_SUPER_SECRET_KEY>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  MYSQL_SERVER: "<YOUR_RDS_ENDPOINT>" # Replace with your RDS endpoint
  MYSQL_PORT: "3306"
  MYSQL_DB_LOGIN: "login_db"
  MYSQL_DB_FILE: "file_db"
  AWS_REGION_NAME: "us-east-1"
  AWS_BUCKET_NAME: "<YOUR_FILES_S3_BUCKET_NAME>"
  LOGIN_SERVICE_URL: "https://<YOUR_CUSTOM_DOMAIN>"