apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets-provider
  namespace: app
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "<YOUR_SECRET_NAME>"
        objectType: "secretsmanager"
        jmesPath:
            - path: MYSQL_USER
              objectAlias: MYSQL_USER
            - path: MYSQL_PASSWORD
              objectAlias: MYSQL_PASSWORD
            - path: SECRET_KEY
              objectAlias: SECRET_KEY
  # Ensure the CSI driver syncs these secrets into a standard Kubernetes Secret
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - key: MYSQL_USER
          objectName: MYSQL_USER
        - key: MYSQL_PASSWORD
          objectName: MYSQL_PASSWORD
        - key: SECRET_KEY
          objectName: SECRET_KEY
